= Pepperの中の人をりんなちゃんにして悲しみをしのぐ〜Pepperがやってきた！ヤァ！ヤァ！ヤァ！その２〜
:published_at: 2016-05-31
:hp-alt-title: RinnaInPepper
:hp-tags: Pepper,Rinna,りんな,Yagasaki,AMI,Vi

こんばんは。矢ヶ崎です。 +
 +
http://tech.innovation.co.jp/2016/05/06/Welcome-Pepper.html[前回のブログ]でご連絡しましたが、Pepper for Bizは、なんと！自律的に成長しません！ +
そこで、その悲しみをすこしでもやわらげるために、Microsoft製の女子高生AIでおなじみ http://rinna.jp/rinna/[りんな]ちゃんに中の人(なかのひと)になってもらって、とりあえずしのいでみよう！おれの心！っていう試みをしてみました。 +
ぼくと同じく、Pepper for Bizで心に傷を負った方は、こっち系のアプローチでとりあえず精神を安定させてみてはいかがでしょうか？

== まずは前回のつづき

身体に青いピンがささりっぱなし！という初歩的なあれで、Pepperくんは調子悪かったようですので、それを抜いてあれこれしたら、調子よく、ふつーのPepper for Bizくんになってくれました！

== 準備

いまのところ、りんなちゃんはLINEかTwitter経由でのみお話できるようです。LINEに連携させるのは非常に敷居が高いので、まずはTwitterにてチャレンジしてみました。 +
簡単に言うと、

* TwitterのAPIを使えるように準備する
* Twitterでりんなちゃんとお友達になる
** DMでお話しない場合は、たぶんお友達にならなくても大丈夫
* Pepperに、我々のお話を理解してもらって、文字にしてもらう
* Pepperで、TwitterのAPIを叩いて、りんなちゃんに対してつぶやく
* Twitterでりんなちゃんの返信を、Pepperにしゃべらせる

というふつーな感じでやってみました。

== TwitterのAPIを使えるように準備する

これは、いくらでもある情報なので割愛します。
「Twitter api 利用」 みたいな感じで調べれば、こんもり出てきますので、やってみてください。
そして、とりあえず、

* Consumer Key
* Consumer Secret
* Access Token
* Access Token Secret

の４つを用意してみましょう。

== Twitterでりんなちゃんとお友達になる

これも、いくらでもある情報ですが、
LINEで友だちになって、りんなちゃんに聞けば教えてくれます。検索して出てくる情報では、 http://usedoor.jp/howto/web/twitter/ai-joshikousei-rinnna-follow/[こんな感じです]。 +
フォローしてもらうと、DMで会話ができるようになりますが、非公開でメンションをつけても大差ないので、どっちでもいいですね。

== Pepperに、我々のお話を理解してもらって、文字にしてもらう

こちらは、Pepperに我々の声を文字にしてもらうわけですが、ふつーにやると、とっても精度が悪い！ +
そこで、 http://qiita.com/JohnTomato/items/0f8469f12a69f9cc8ac6[こんな感じでWatsonに声を認識させれば非常に精度があがる]という素晴らしいやり方があるっぽいのですが、そうすると、いよいよPepperがただのマイクとスピーカーになってしまう感が大きく、悲しみをやわらげるという目的から遠ざかってしまうかもしれないので、今回はPepper本体の認識にたよることとします。

Pepperの開発を行う基本的な方法は、「Choregraphe（コレグラフ）」というソフトを使うということなのですが、この中の部品でDialogというPepperと会話する用の部品があり、そこで一応我々のお話を文字に変換することができます。ので、今回はこれを使ってみます！

== Pepperで、TwitterのAPIを叩いて、りんなちゃんに対してつぶやく


== Twitterでりんなちゃんの返信を、Pepperにしゃべらせる

== いったん動くようになったもの

== 既存の問題点

* 反応が悪い！

* TwitterのAPI制限に引っかかる！

ということで、Pull Requestや https://twitter.com/Yaggytter[@Yaggytter]までコメントいただけたりしますととっても嬉しいです！のでお待ちしております〜 +
ひとつよろしくお願いいたします！

つづく？

