= AWS re:Invent2016初日！(re:Invent2016シリーズ②)
:hp-tags: AWS,re:Invent2016,Las Vegas

お久しぶりです、中村です。


今オザサと一緒にAWS re:Invent2016に参加するために
アメリカへ来てます！

今日初日だったので、どんなイベントなのか、お伝えしますね。

### 開催地はラスベガス！

毎年ラスベガスで開催されているそうでして、今年もラスベガスにて開催されます。

空港にもre:Inventの広告が出ていたのでテンションあがりました！
ちなみにスロットマシンもありました(笑)

メイン会場はベネチアンホテル！
空港からバスで20分くらいのところで、ホテル内にカジノやゴンドラがある超豪華なところです。




=====写真載せる=====



こんな場所で5日間も開催するなんで、本当にamazonすごいなぁと思い直しました。


### まずはREGISTORATION

初日なのでまずは受付を済ませます。

registorationブースに行き、パスポートを提出すると顔写真付きのパスをもらえました。
画像は事前にサイトからUPしたものですが、UPしていない場合にはその場で写真撮影をしてくれるみたいです。

ちなみにストラップの色が何種類かあるんですが、我々は黒でした。
パートナーの方は水色だったんですが、その他はちょっと分からず。
緑、オレンジ、白があったのでちょっと気になります。


=====写真載せる=====


そしてお待ちかねのグッツを。。。と思っていたのですが、何もくれません！
噂ではパーカとかがもらえると聞いていたのですが受付の男性はニコニコしながら
「next!」と言ってるし。。。

思い切って聞いてみると、別の場所で渡すとのこと。もう無くなってしまったのかと思ったのでホッとしました(結構まじで笑)

ゲットしたのはこちら！

パーカー&echo dot！ゲットだぜ！


=====写真載せる=====



### セッション会場に気をつけろ！

re:Inventの流れ簡単に説明すると、

1.事前にセッションを予約しておく
2.セッション会場の入り口でパス確認してもらう
3.セッションを聞く

こんな感じです。（フツーです）

事前にセッションは予約しておかないといけないと聞いていたので出国前に登録しておいたのですが、その時は会場の規模など分からずに内容だけを見て登録をしていました。

その結果。。。

#### 移動ばっかり

になってしまいました。（とほほ）

メイン会場のベネチアンホテルとサブ会場のミラージュホテルはなんと片道徒歩20分！
いや、25分くらいは歩きました。（特に最初は場所が分からずにかなり時間がかかりました）

そして今日の午後のスケジュールがこちら。

13:00 - 14:00 ミラージュ
14:30 - 15:30 ベネチアン
16:00 - 17:00 ミラージュ
17:00 - 19:00 ベネチアン
20:00 - 21:30 ベネチアン

完璧に失敗です。
re:Invent2017に行く方は会場をなるべく合わせておくことをお勧めします。。。


### セッションの雰囲気

会場によって大分違いました。ホテルが違ったりするので当たり前なのですが、それ以上に通常はショーなどで利用していそうな場所だったりと、さすがラスベガス！といった感じでした。


=====写真載せる=====

ちなみに一部のセッションでは翻訳機での同時通訳もあるのですが、基本的には英語のみ。
ただAWSのアイコンが出てくるので、全く分からないことはありませんでした。

=====写真載せる=====


個人的にはDatadogのMatt Williamsさん（Evangelist)のスピーチがとても素敵で気に入りました。

=====写真載せる=====


あとJames Hamiltonのイベントは席に着くとポップコーン&ビールが配られ、前座でライブやっていたり。。。
まさにお祭りといった感じで最高でした！




明日は新発表などもありそうなのでとても楽しみです。


ちなみにラスベガスは乾燥がひどく、水の消費が半端ないところでした。



こちらからは以上です！


