= 新卒未経験のbigenがプログラムの構造って面白いって思った話
:published_at: 2016-12-16
:hp-alt-title: ProgramingArchitectureAndMath
:hp-tags: MVC,Architecture,Math,Bigen

はじめまして、*bigen*です。

今年の１０月から入社した、*新卒（ほぼ）未経験*のひよこエンジニアです。 +
軽く経歴を紹介しますと、

- 1991年9月  京都に生まれる
- 2010年4月  PCで遊ぶのが好き（コーディングとかはしない）なので、京都大学工学部情報学科へ入学
- 2013年4月  麻雀が好きなので留年
- 2014年7月  麻雀が好きなので最高位戦日本プロ麻雀協会に入会
- 2016年9月  麻雀はいったん休憩にして、真面目に数学を勉強して卒業
- 2016年１０月2.5留年を経て、イノベーションへ入社

という感じです。
現在は弊社の*ListFinder*という*マーケティングオートメーションツール*の開発を行っています！+
 +
大学では線形代数とかをやっていたので、 +
研究で使う計算（積分したり行列計算したり）ぐらいのプログラムは書けたんですが、 +
プロダクトやアプリを作るような経験は全くなしでした。 +

そんな僕が、真面目にプログラミングを初めてみて、 +
*「やっぱり計算機とかプログラミングの概念って学者が作ったんだなぁ」と感じて面白かった話*です。 +
 +

#### 「モデル」という言葉

例えばごく基本的な考え方として「*MVCモデル*」というものがあります（最近勉強した）。 +
サービスの構造を +

1. 目に見える部分（*View*)
1. なにか入力を与える部分(*Controler*)
1. なかでごちゃごちゃやる部分（*Model*）

で分離しようという考え方ですが、 +
最後の「なかでごちゃごちゃやる部分」に「Model」なんて名前をつけるのはいかにも学者っぽいですね。 +
 +
 学術領域では「入力と出力にある関係があった時に、決められたある枠組みの中でその入出力関係を記述したもの」をモデルと呼びます（ちょっと語弊があるかも）。 +
 小難しいことはおいといて、普通に生きてたら「モデル」なんて言葉は芸能人とかプラモデルぐらいにしか使わないわけですよ。 +
 そんな言葉が普通に出てきてるのが面白いなぁと思いました。 +
 +
 
#### オブジェクト指向って数学そのもの

あと、「**オブジェクト指向**」という言葉も勉強中で超難しいなーとか思ってるわけですが、 +
「クラス」「サブクラス」といった概念は、よく考えたら線形代数でモロに出てくる概念でした。 +
 +
 このことに気づいた瞬間、 +
 様々な「クラス」が何重にも折り重なった複雑怪奇なフレームワークも、 +
 線形空間に照らし合わせて考えればすごく理解しやすくなりました。 +
 以下具体例込みでもう少し説明したいと思います。 +
 +
語弊を恐れず超ざっくり言うと、 +
線形代数とは 「足し算と掛け算が**普通に**使える変数と関数」だけを扱う数学です。 +
 何言ってんの？って感じるかもしれませんが、 +
 「a+b ≠ b+a」とか「a(b+c)≠(b+c)a」になるような数学もたくさんあります。 +
 +
なので、変数一つ扱うのにも、 +
まずは「右から足しても左から足しても結果は同じやつだけ使おう」とか +
「点が２つ存在してたら、それだけで距離は一通りに決まる空間で話をしよう」 とか +
そんなあたり前に見える話をきっちり決めとかないと、 +
Aさん：足し算しただけなのに結果がおかしいぜ！ +
Bさん：そんなわけないだろ！どれどれ・・・・えっ！右から足したり左から足したりしてんの！？そりゃおかしくなるだろ！ +
みたいに矛盾が生じて議論が進まないんです。 +
 +
オブジェクト指向も思想は結構似ていて、 +
まずは「変数が２つあったら、距離メソッドが絶対使える前提で話をしよう」とか、 +
「tb名とアクションの情報（プロパティ）は絶対もってる命令文だけを扱うぜ！」とか、 +
あらかじめ議論のフィールドを決めてから仕組みを作んないと、 +
「絶対に矛盾がない（絶対にエラーがおきない）」状態は維持できない。 +
だから「このグループからとってきた要素だったらこういう風に使っていいですよ」 +
っていう「前提となる集合」と「その要素」の関係をプログラム言語で実現しようというのが +
オブジェクト指向なんだろうな、と思っています。

#### まとめ

というわけで、数学とアーキテクチャの話はすごい共通点が多くて、 +
あんなに苦痛だった数学の勉強もやはり役に立つもんだなぁと思って面白かったお話でした。 +
 +
ちなみに今回はいきなりコーディングに関するブログでしたが、 +
個人的には組織の成果を最適化する仕組み作りなんかに結構興味あって、 +
今後そういった「俺はこういうのがやりたいんだ！」という話もしていきたいと思っています。 +

次回をお楽しみに！
