= エンジニアキャリアパス問題
:published_at: 2016-5-13
:hp-alt-title: EngineerCareerPath
:hp-tags: Tsukamoto,Engineer,CareerPath

定期的にネットで上がってくる「エンジニア35歳定年説」という説があります。

まあ、若手だった層も時が経てば年齢が繰り上がってくる以上、循環的に話題に上る現象も当然なのかもしれません。
そして、ここ数日またこの説に関して話題に上がっているのを読み、思うところあったので、私も中堅を過ぎたエンジニアのキャリアパスについて所感を書いてみます。
（決して会社の見解ではございません）

まずこちらの記事 http://kwappa.hatenablog.com/entry/2016/05/10/115017[「健康は命より大事。」]

Health Orientedエンジニアとしては、これに尽きてしまうので、ここで終了でもよいくらいなのですが、ボツ原稿になるでしょうからもう少しだけ。



## 前提知識
（特に他職種の方だと）知らない方もいらっしゃるかと思いますので説明しますと、

SIerや過当競争下にある人員不足のスタートアップ企業などでは

- 納期に追われ精神的に追い詰められることによる心身への負荷が高い
- 管理職にならないと給料が上がらない（詳しくは http://www.ryuzee.com/contents/blog/7089[Ryuzee.com]にて）

- 技術の流れが早く継続的な学習が必須であるが、加齢とともに学習能力（というか記憶力？）が落ちていく

などの理由から、35歳くらいが限界じゃないかと叫ばれている説です。
自分がエンジニアになった頃から言われているような記憶があります。

    余談ですが、弊社は元々「仕事の効率化」を目的としていることもあり、私の直近残業時間は0（極限値）です。


### がしかし、一般化できていない
既にお気づきかと思いますが、個人差、会社差に依存するため千差万別とも言え、いわゆる**主語が大きい**言説になってしまっています。
そもそも「エンジニア（元はプログラマ）」という括り（機械エンジニアからソフトウェアエンジニアまで含む）が大雑把すぎる時点で、発議するほどでもないテーマであり、
時代の移り変わりもある中で、ネタと化してきている側面もあります。

### その上で

個人的に言えば、当てはまる部分もあるので、自分なりの対処法も含め、以下にまとめてみました。

## 合致する部分
### ライフスタイルの変化
上のリンク先でRyuzeeパイセンも述べておられますが、30代にもなると結婚する人の割合が増えてくるのは確かです。
（35歳以上だと男女ともに半数を超える： http://www.stat.go.jp/data/kokusei/2010/kihon1/pdf/gaiyou1.pdf#page=23[総務省統計局HP]）

家庭をもつと勉強時間の確保は難しくなります。若いころ培った知識や経験だけでやっていけるような職種と比べれば、
単純に技術を追求するキャリアの継続が難しい点はあります。

ただ、時間の使い方や「何に投資すべきで何に投資すべきでないか」といった判断力は確実についているかと思いますし、
チーム全体を効率化して自分の仕事を減らすなど、
日常や仕事の中での無駄を省くなり効率化してうまく時間を捻出することができます。

これこそがエンジニアリングです。

    余談ですが、弊社開発部門はセルフタイムマネジメントにより、私の直近残業時間は0（極限値）かつ週2で保育園のお迎えに行っております。

### 学習能力問題
新人の頃と比べると、覚えれる量及び速度が減ったような気がしています。
よく考えると、それこそ当時は何もないスポンジのような段階だからこその吸収力だった気もするし、自分の感覚なんて曖昧なものです。

新しい技術も例えば、新しくDockerのことを学ぼうとしたとき、
- Linuxコンテナを理解している
- AWSのAMIのイメージに近い
といった既存技術の知識があるだけで、自分の頭の中を補完するだけで済み、随分と勉強することは楽でした。

    どのような技術やソフトウェアも、開発された理由や経緯があるので、歴史のピースを埋めていく作業

と捉えると学習しやすく、まあ結論、歳をとってもプラマイゼロかなと。

「教えてもらえる環境かどうか」というのは要素としてとても大きいですが、これも会社依存の問題なのでここでは置いておきます。




### キャリアパス問題
エンジニアという人種は比較的報酬に無頓着とまでは言わないけども、”いいモノを作る”原理主義のようなところがある。（あくまで周辺観測です）

”いいモノを作る”エンジニアが会社に目に見える利益を生むのであれば、何も問題はないでしょうが、
そう単純に正比例するわけでもないのが現実です。（そもそも”いいモノ”に対する価値観が一致していない）

また、目に見えない”いいモノ”を評価できる組織なのかという問題もあります。

上述のライフスタイルの変化とも関連してきて、家庭をもつようになれば、そこそこの給料が必要になってくる。
「さぁどうしよう」お恥ずかしい話ですが以前は自分もざっくりこんな感じでした。

そして私も一時、マネージメント寄りになったことがありますが、正直向いてるとは感じませんでした。
やれないことはないし、そのほうが会社のためになるのであればやるけども、エンジニアリングで解決している手応えが欲しくなってしまう。

自分の力で出来ることは限られてくるし、色々と逡巡した結果、ひとつ導き出した選択として

**この会社に貢献すれば、”いいモノ作り”に繋がっていく** と思える会社に入ること

そういった現場であれば、自分に向いていなさそうなことでも、自己実現の目的のために力を発揮できそうだし、好きなようにモノを作らせてもらって評価してもらえるなら尚ハッピーかと思います。

思ったことを連々と書いていったらこんなにまとまりがなくなってしまいましたので、本日はこのへんで。

こちらからは以上です。


管理職という役割の必要性はなかなかなくならない
かといって上位エンジニアの必要性はあるのか

スペシャリストという職位

結局、役割が違う人たちを相対的に給料決めたりするのがおかしいのでしゃ
