= re:Inventひいては海外に行くということ(re:Invent2016シリーズ)
:published_at: 2016-12-09
:hp-alt-title: reInvent-and-that-going-abroad
:hp-tags: AWS,re:Invent2016,Las Vegas,Ozasa

さて、行ってきましたre:Invent2016。

イベントの最中にもブログを更新しておりましたので、 +
ざっくりした雰囲気はそちらを見ていただきたのですが、 +
本ポストでは初の米国滞在と初のre:Inventが僕が何を感じたかを書いてみたいと思います。

まず、**日本に帰ってきて感じたこと**

* 道が狭い(色々近い)
* 人が多いように感じる
* 思ったより暖かい

です。

うん、結構な変化があったようです。 +
とはいえ、もうちょっと詳細に書きましょう。

## 初の米国滞在

自分自身、卵・牛乳アレルギーで英語もあまり得意ではないということもあり、
海外に行くことを少し嫌厭している節が正直ありました。

ただ、初の米国は、そんな僕を変えてくれました。

まず街やそれに付随するサービス(仕組み)などなどですが、 +
何もかもが巨大で、どことなく無作法で、でもそれでいてとっても効率的な感じがしたのです。 +
巨大でいえば、ホテルから隣のホテルまでの移動で、僕が普段出社にかける時間よりも長い時間歩くことになるとは思いもしませんでしたし、 +
バスも2台分連結しているようなデザインでしたし、 +
スタバの焙煎機(?)もディズニーか何かの装飾かってくらいの巨大さでしたし、 +
美術館に至っては広すぎて歩き疲れて半寝しちゃったくらいです。

また人柄ないしキャラクターにも大きな違いを感じました。 +
多くの人がかなり気軽に話しかけてくるのです。 +
日本ではあまり無い光景ですよね。 +
いいステッカーだな、なんだそのパーカーは、飯はうまいか、などなど

本当にみんな気さくに話しかけてくれます。 +
I love youすら結構気軽に言うみたいです。というか言われました。 +
つまりその、なんと言いますか、日本で言う「積極性」とはちょっと違うコミュニケーション能力を感じたわけです。 +
それはセッション会場でもそうです。 +
発表者へのレスポンスも、セッション終了後に質問へ並ぶ様子も全てが日本でのそれとは違っていて、表現が難しいですが、**ポジティブ**に見えました。

あと、これも現地で感じたことなのですが、 +
日本と韓国の企業向けセッションでは、 +
参加者はどういうわけか前の方から座らず、中間から後ろよりの席から埋まっていくのです。 +
他のセッションではガンガン前の方から埋まっていました。

手を上げないとチャンスはないという精神なのだろうかと勝手に思いました。

そしてそんな世界の人々を見て、自分ももっとチャレンジしていこうと思えましたし、 +
世界を知るということはこういうことでもあるのかなと感じました。

## re:Invent
さて、re:Inventのお話です。 +
前々から「re:Inventは学習型のカンファレンスである」とAWSの方々は何度も仰っておりましたが、
正直行くまではそれが意味するところを理解できていませんでした。 +
しかし、今回参加してみてその意味がはっきり分かりました。

本当に多くのエンジニアが学ぶことに熱中しており、 +
またそのための環境もしっかりと提供されているのです。 +
そして、AWSの社員の方々もユーザとの交流によって、彼ら自身もユーザから学んでいることがしっかり分かりました。

自分自身もキーノート、セッション、ネットワーキング、と
かなり多くの情報が入ってくる中で、
なんとか自分の頭の中で咀嚼しながら、もしくは人と話しながら、
より良い未来を想像したり語ったりするのは本当に貴重で大切な体験でした。 +
(飲み会ですら皆がAWSのことを、そして技術のことを本当に好きなんだなってことが伝わってくるくらいでした)

とても良い学びの場だと思えましたし、
帰りの飛行機を待っていた時、re:Inventが終わることを実感できてしまい、
とてもとても淋しい気持ちになったのは、その分楽しかったってことなんだなと思います。

## これからのこと

さて、
今回の旅で、世界の広さ、エンジニアの熱量、を肌で感じることができました。

その中で +
もっと前に出ていかなくてはならない、 +
もっと発信し何かとぶつかることで高めてあっていかなければならない +
と、より強く思うようになりました。

特にエンジニアのいる世界の変化は激しい中で、 +
re:Inventはきっと日本の多くにとってはまだまだ未来で、 +
でも世界にとってはスタンダードのちょっと先くらいなんではないかと強く危機感を覚えたのです。

正直、僕はまだまだ新サービスの必要性もしくは革新性をしっかり実感できるレベルに達していません。

でも、現地のエンジニアの熱気に当てられてしまったのもありますが、
早くその段階まで自分を進めなければならないという焦燥感がありつつも、
わからないことだらけの世界のその先も結局はわからないことだらけで、
飽きることはなさそうだな、なんていう風にも思ったりします。

まぁ色々書きましたけれども、 +
何はともあれ**来年も絶対行きたいなぁ**と思うわけです。

カジノにお金を預けてしまっていますしね。


#### 最後に
現地で僕らと関わってくださったすべての方々、 +
僕を送り出してくれた会社の皆様、 +
そして僕が不在時にも支えてくれたメンバーの皆様に最大限の感謝を。

どうにか恩返しできればと思います。

こちらからは以上ですが、これからもよろしくお願いいたします。