
= LogZoomとFilebeatでログ収集！

さてこんばんは。
矢ヶ崎です。
みなさんいかがお過ごしでしょうか？


Pepperの続編は次回！ということで、Go言語社内エバンジェリスト(自称)のわたくしが、Go言語に関わることを一切書いていないことに気が付きましたので、今回はGo言語にかすってることを書きたいと思います。

Go言語、みなさん使っておりますでしょうか？

わたしの場合は、社内のイベントで使うプログラムは全てGoで書くようにしております。まだまだGo言語社内エバンジェリスト力が弱いわたくし程度では、弊社のプロダクトにはなかなか採用できていないのですが、それでもなんとかGoに関わっているようにしている次第でございます。

そこで、今回は弊社の一部プロダクトで採用している数少ない事例として、Go言語にかすっているものをご紹介いたします。

== オートスケールなどなど

クラウドの時代って、ほんと便利ですよね〜。サーバも簡単にオートスケールなどで構成できて、簡単ポンですよね。

でも、あるあるで、「スケールインした時にログ消えちゃうじゃん！」問題とか、「リアルタイムでログ集計したいんだけども・・・」問題とかよく聞きますよね！

== だとすれば、ログ収集

そこで！みなさんログ収集＆保存しているかと思います。日本のWeb系では、たぶんFluentdとかがとっても有名で、こちらを利用してログ収集していたり、Logstash使っていたり、rsyslogでがんばっていたりするかと思います。

しかし！LogstashやFluentdは、個人的には重い！！！

rsyslogやsyslog-ngは、シンプルすぎちゃってつらい！

そんなお悩みをかかえていらっしゃるかと思いますみなさん。

そこで逆に、「Goのやつって速いっていうじゃん〜」とかっていう安易なキーワードがあると思うので、それに便乗させていただき、Goで書かれたログ収集ツールを利用することにしました！

== LogZoom登場

LogZoomというログ収集するツールがあるではないですか！

https://github.com/packetzoom/logzoom

Outputsのところを見ると、ElasticSearchとかS3とかあっていい感じ〜

しかし！Inputsのところを見ると、FilebeatとRedisしかない！いわゆるログファイルは読めないのか？読めるのか？読めないのか？

== Filebeat登場！

そこで、Filebeatが登場します。

https://github.com/elastic/beats

Logstashと同じくElastic社のプロダクトなのですが、また、これもGoで書かれています。

=== くぁ〜〜〜

これはたまらんです。そして、ログファイルを読んで、LogZoomにLumberjackというプロトコルで送れるようです！ほんとはLogstash用にできているとしても！

== Goで書かれたプロダクトの簡単さ！

あんまりGoを使っていない方のために、ちょ〜いい加減かつ簡単にGoで書かれたプロダクトを動かすためにやることを書いておきます。これが、またGoのすごいところなんですよ！

==== Goをインストールする

ここからダウンロードするか、brewとかyumとかでインストールしてください。

https://golang.org/

==== GOPATHを設定する

Goのソース一式などなどを入れておく場所を指定するものとして、GOPATHという環境変数を設定します。

```
$ mkdir $HOME/go
$ export GOPATH=$HOME/go
```

今後、このGOPATHに、いろいろなファイルが入ってきます。

==== go get で取ってくる






```
$ go get -u [URL]
```

=== 幸せなログ生活

そんなこんなで、今では弊社の某プロダクトで幸せなログ生活が送れております。








軽い！

を書く予定
矢ヶ崎
