= 文系男子がフィリピンにアプリを作りに行ったお話
:published_at:2016-06-10
:hp-alt-title: IPhoneAPPinPhilippines
:hp-tags: FirstPost,Objective-c,kohe,IPhone

近藤康平:マクドナルドで３年、雀荘で３年バイトを経験。雀荘内のランキング１位まで上り詰める。スマホを改造してビジコン入賞。19歳から株式トレードの勉強を始め、株式の塾に入る。マレーシアで新規マーケティング事業立ち上げ。フィリピンでプログラミングを学び、アプリを作ったりしている。プログラミングと株式トレードの勉強と実践を主に行っている。現在はイノベーションのエンジニアである。

教科書が高く、財布の中身がギリギリだった私がフィリピンに行き、教科書を簡単に安く買えるiPhoneアプリを作りました。その中での経験をお話します。
===Amazonなら、教科書を安く買える
4月、大学生である私にとって憂鬱な月だった。なぜなら教科書を買わなくてはいけないからだ。当時雀荘のバイトで生活していた私にとって、2~3万の出費はかなりの痛手であった。そのくせ講義でその教科書が使われないとなると怒りが沸き上げるのであった。
「Amazonで買えば安く買えるよ」
高校時代の友人からの言葉だが、まるで天からの囁きであった。
教科書(2160円)が
中古1円で買えたりするのだ。
トータルの教科書を買うコストが半分以下まで下がった。しかも、この事実を多くの友人（大学生）は知らなかった。これを広めるのは私の役目だと思い、手始めに私の大学専用の教科書（値段）比較サイトを作った。
多くの人に知ってもらうためTwitterで1,000人くらいフォローしたところツイッターアカウントが凍結した。そう、これは規約違反なのだ！即座にTwitterに謝罪メールを送り、凍結解除。何とかアカウントが生き残った。しかも1000人フォローしたままである。ラッキー！
そのアカウントで作ったサイトを広めることにより、学生は本を安く買うことができる。そして、私にはお小遣いが入る。このwin-winの関係を築くことができた。
ここで私の熱は止まらず、次は全国版を作ろうと考えた。しかし、知識不足のせいで一旦断念。全国版を作りたいという思いを心の片隅に持ったまま生活をすることになる。

===フィリピンでプログラミング学校で特訓を受けた
そんなある日、Facebookの広告で　IT×英語をフィリピンで学ぼう！　的なものが流れてきた。しかも、ITの学習内容はiPhoneアプリ開発である。これはフィリピンで全国版教科書比較アプリ作るしかない！と決意。この語学＋プログラミング学校（学校名:NEXSEED）に速攻応募。
フィリピンで2ヶ月間かけてアプリを作ることになったのである。iPhoneアプリを作るにはobjective-cを学ぶ必要がある。しかし、私のプログラミングの知識は文系の子が講義で習うくらいであった（プログラミングの基礎の基礎程度しかない）。
2ヶ月で間に合うのか？疑問が頭によぎった。そこで、私は2つの明確な目標を立てた。「アプリを作る！」に加え「独学でプログラミングが出来るレベルにまで行く」
目標を掲げたことでやるべきことが明確になった。自分の分からないことを全て、先生に聞けばよいのだ。目標を立てた瞬間から、講義＝質問の時間に変わった。10人程度のクラスで他の生徒の5倍以上は質問した。
講義を受けるだけで間に合うわけがない。講義が終わってからはひたすら予習復習をした。分厚い教科書も、予習のみで1周間で終わらせる勢いでやった。
毎日、寝るまでは知識のインプットをしまくった。分からないことがあると、プログラミングの先生をご飯に誘いまくって解決しまくった。先生のバグ修正を何度も見たおかげで、講義では習わない「バグの箇所の見つけ方」を身につけることが出来た。
この知識を講義で学ぶことは難しいが、かなり重要な知識である。フリーランスの先生から学べたのは大変良かったと今でも思う。そんな日々を過ごした。
1日10時間以上の勉強、英語全然使えない、ストリートチルドレンに絡まれる、タクシー乗ったら知らない場所に連れてかれるという楽しい環境だった。
===帰国後、App Store５回もリリースに挑戦
そしてつい完成！　App Storeへリリース申請をした。
しかし、結果は認められず…。バグが有るとのこと。
日本で1人でバグをなおすことになった。ここで、先生から学んだ「バグの箇所の見つけ方」が生きる。エラーが出た時、自分でミスを見つけることができる！
1人で調べ、1人で作り上げる。この作業が出来るようになっているのだ！高い金を払って学んだかいがあった！考え、調べ、実行し、バグをなおす。見事にPDCAサイクルを1人で出来る。
※PDCAサイクル
Plan：計画を立てる
Do：実行する
Check：評価する
Action：改善する
その後も修正しては申請、リジェクトの繰り返し。
なんとか、これを5回繰り返し何とかリリース！
この時既に半年が過ぎていた。でも、うれしい！
↓のリンクから本（実際は本以外でも何でも）を中古料金で安く、複数サイトから比較するアプリインストールできます。
教科書比較App By Kohei Kondo
 

