
= エンジニアの卵が分かりやすいと感じているおすすめのプログラミング学習サイト
:published_at: 2016-06-10
:hp-alt-title: programming-study
:hp-tags: FirstPost,oyaizu,programming,web-service


はじめまして、株式会社イノベーションの小柳津と申します。約2ヶ月前に入社し、最近は立派なエンジニアを目指して、日々研修など奮闘中でございます。 +
 
私はエンジニアとして入社したのですが、実は弊社に入社するまでは、プログラミングどころか、パソコンにもあまり触れたことのない人間でした。ですが、入社前にありがたいことに人事の方からエンジニア配属というありがたいオファーを頂き、「よし！プログラミングを勉強するぞ！！」と思い立ったのはいいのですが、「どうやって勉強しよう…」という壁にぶつかりました。 +

当時の私は知らなかったのです。世の中にはプログラミング学習サイトという便利なものがあることを。ちなみにそれにたどり着くまで「エンジニアになるしブラインドタッチくらいはできるようにならなきゃカッコ悪いや」と思い、タイピングの練習をしていました。確かに必要ですけど、直接的なプログラミングの勉強ではないですよね… +

今回ブログではエンジニアの卵な私だからこそ、利用していてこれはいい！と思うプログラミングの学習サイトをご紹介します。個人的な評価になりますが、以下の5つの基準でご紹介します。 +

*	学習レベル
*	分かりやすさ
*	楽しさ
*	対象言語
*	価格


== 1,Progate

link:https://prog-8.com/[progate]はプログラミングって何？という状態の方からでも始めることができる学習サイトです。 +

私はこのサイトから学習を始めました。分かりやすいスライドがあり、まずそれを読み、課題をこなしていく。課題はオンラインエディタにプログラムを直接入力していく方式で正解不正解を自動で判定してくれます。課題をこなしていくとあら不思議、おしゃれなサイトができちゃった！という楽しく学習ができるサイトです。手を動かしながら、学習できるのがとてもよいところですね！ +

しかし、とても分かりやすい反面、実行環境を揃える必要が無いので自分で揃える方法がわからなかったり、無料で学習できる分では不十分といえる量しか学習できなかったりというところが問題点といえるでしょう。 +

最近では対応する講座が大幅に増え、月額980円という価格で全ての講座が受講できることから、有料版でやってみるのもアリだと思います。

|====================================
|学習レベル  |  初級（有料版なら中級レベルまで） 
|分かりやすさ|  [yellow]#★★★★#☆ 
|楽しさ        |  [yellow]#★★★★#☆
|対象言語    |  HTML, CSS, PHP, JS, JAVA, Ruby, Swift, Pythonに対応 
|価格         |  無料（有料版は月額980円） 
|====================================



== 2,ドットインストール

link:http://dotinstall.com/[ドットインストール]は言わずもがな良く知られているプログラミング学習サイト。 +

あらゆる言語の学習ができ、1つ1つの言語に対して講座数も豊富に取り揃えられています。講座の形式は動画で1回の授業が3分で終わるため、スキマ時間でも勉強できる。私は通勤時間などに動画を見て勉強しています。携帯でも動画見られるがとてもよいですね！ +
有料版（月額980円）だと更に受講できる講座数が増え、1つの言語に対して、なかなかのレベルまで学習することが可能です。動画はとても早口で進んでいき、どんどん進んでいってしまうので、動画を見た後の復習が大切ですね。 +

Progateとは異なり自分の手を動かさないで勉強ができてしまうので、動画を見た後に自ら手を動かして復習できるかがポイントです。

|====================================
|学習レベル   |  上級レベルまで
|分かりやすさ  |  [yellow]#★★★#☆☆
|楽しさ         |  [yellow]#★★★#☆☆
|対象言語     |  多数言語に対応
|価格           |  無料（有料版は980円）
|====================================



== 3,CodeIQ

link:https://codeiq.jp/[CodeIQ]は「3の倍数のみを出力するプログラムをかけ」や「素数を出力するプログラムをかけ」などアルゴリズムの問題を掲載したサイトになります。 +
つまり演習用サイトで、ある程度基礎を抑えた上でないと難しい部分もあります。Progateやドットインストールで基礎を抑えてコーディングがある程度できるようになってきたら、このサイトを利用するのがおすすめです。 +

勉強したことが実践できるか、学習サイトを利用しただけでは分からない知識などを、問題演習を元にして調べながら学習することがコーディングの上達に繋がるはずです！ +

問題も面白いものが多く、楽しくコーディングができるのがよいですね！

|====================================
|学習レベル   |   − （演習サイトのため）
|分かりやすさ  |   − （演習サイトのため）
|楽しさ         |   [yellow]#★★★★★#
|対象言語     |   多数言語に対応
|価格          |   無料
|====================================



== まとめ
Progateやドットインストールを用いてプログラミングを勉強し、CodeIQで実践してみるのがおすすめです。個人的にはおすすめの学習順番としては、以下の順番です。 +

.  Progate（無料版）
.  ドットインストール（無料版）
.  Progate（有料版）
.  ドットインストール（有料版）
.  CodeIQ

私と同じように未経験からエンジニアになりたい！と思う方はぜひ参考にしてみてください。卵から早く立派に羽化できるよう頑張って参りますのでよろしくお願いします！ +

もし未経験からエンジニアになりたいと思っていた！これ以外にもおすすめの学習サイトはないの？と思った方、是非是非、link:https://www.facebook.com/profile.php?id=100007134556047[小柳津]までご連絡ください〜 +

今回はここで失礼します。
