= WordPressサイトのhttps化をした時のお話など
:published_at: 2016-05-26
:hp-alt-title: Such-as-the-story-of-when-he-turned-into-https-of-Wordpress-site
:hp-tags: SecondPost,Oz,https,WordPress

こんにちは。  
弊社エンジニアグループでは**もう**一番若手ではなくなったの3年目エンジニア小笹です。 

先日弊社で運営している https://www.innovation.co.jp/b2blog/[BtoBマーケティングイノベーション] をhttps化したのですが、 +
その時考えたり感じたりしたお話をさせていただればと思います。

## 前提
https://www.innovation.co.jp/b2blog/[BtoBマーケティングイノベーション] とさらっと書きましたが、 +
弊社が運営しているBtoBマーケティングの情報発信用ブログのことです。

社内のメンバーが個々人の得意なことや調べたことを記事にまとめたものや、 +
外部のイベントに参加した際のレポートなどを公開しております。

タイトルに「ブログ」とあるように +
基本的に記事投稿がメインの作業になるためWordPressが採択されております。

## WordPressって何？
よく聞くとは思うのですが、おさらいです。

WordPressはオープンソースのブログソフトウェアで、 +
最初のバージョンが出たのが2003年ということですから +
もう10年以上前からあるソフトウェアになるんですね。

感覚値ですが、
日本で流行ってきたのはここ5年以内という感じでしょうか？ +
私も情報収集のため色々なサイトを回遊しますが、WordPressサイトがかなり多いように感じます。 +
「famous 5 minute install」というフレーズにあるように手軽さなどが導入数を増やしたきっかけでしょうか。

ちなみに開発者のMatt Mullenweg氏は日本にもよく来てくださっているようで、 +
雑誌なんかにもたびたび載っていらっしゃいますから見たことあるかもおられるのではないでしょうか。 +
// 32歳、とってもお若いです。

## 必要な作業
さて、弊社のブログとWordPressについてはざっくりご理解いただけたかと思いますので +
構成をざっくりお伝えすると

ELB →　EC2　 ←→ 　RDS

のようになっております。

そして弊社の場合httpsで運用するには下記の作業が必要でした。

. 開発環境の構築
. 証明書の設置
. DB内のパス書き換え
. phpファイルなどのパス書き換え
. .htaccessの設定

### 1,開発環境の構築
まず対象のEC2インスタンスのAMIをとって、 +
そこから安め(t2.micro)のインスタンスを立ち上げます。

次にRDSのスナップショットをとってEC2同じ感じでとったやつから立ち上げます。

先ほどのEC2にSSHで接続してwp-configファイルを書き換え見に行くDBを変えます。

次にELBを作成して、EC2を接続します。 +
作成したELBのDNS名をdigってでてきたIPをhostsに書いてwww.innovation.co.jpでアクセスできるようにしておきます。

こんな感じで開発環境がサクッと作れてしまいました。びっくり！！ +
`(実際には色々調べたり教えてもらいながらだったのでかなり時間かかってます)`

### 2,証明書の設置
作成したELBにSSL証明書を設置しましょう！！
AWSの管理画面をぽちぽちすればできてしまうので楽チンです！！

### 3,DB内のパス書き換え
開発環境なのでゴリゴリやっていきましょう！
ミスったらまた作ればいいのです！！

という精神でDB内のデータも書き換えていきます。 +
WordPressは設定情報やメディア(画像)のパス情報などをDBに保存するようになっているため、 +
http:〜で保存されているデータはかなりの量あります。 +
(参照URL:http://wpdocs.osdn.jp/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E6%A7%8B%E9%80%A0)

なのでUPDATE文で一括で書き換えてしまいましょう。 +
対象はざっくり以下の通り

* wp_options.option_value
* wp_posts.guid
* wp_posts.post_content
* wp_postmeta.meta_value

トランザクションはって、慎重かつ大胆に進めていきます。 +
*えいやっ！*

### 4,phpファイルなどのパス書き換え
DBの中身が書き換わってもheader.phpなどに直でリンクを書いているパターンもあると思います。 +
ブログの場合はそこまで画面数も多くないでしょうから、ここはチクチクやっていきます。

### 5,.htaccessでリダイレクトの設定
httpできたユーザをhttpsの環境にリダイレクトしてあげましょう。 +
これができれば終了です！！

が、

## 困ったこと
*いざ、アクセスするとリダイレクトループに入ってしまい表示がうまくいきません……*

試しに3の工程でやったhttps化の逆にhttp化して5のリダイレクトを切ってみます。  +
するとリダイレクトループには入らなくなりました。

なぜ！？

色々調べてみました。 +
しかし、WordPressってユーザ数も多い上にエンジニアではない方が、 +
疑問をそのまま投稿していることなどが非常に多く、ネットの情報が煩雑になっており、 +
なかなか欲しい情報にたどり着けません。

それでもキーワードを変えたり、サーバのログやブラウザのログを見ていって、 +
WordPress側でリダイレクトしていることがわかりました。

それを元に検索やらごにょごにょしてみると +
*is_sslが問題っぽいことが判明しました。*

## 解決策らしきもの
[source, rust]
----
function is_ssl() {
  if ( isset($_SERVER['HTTPS']) ) {
    if ( 'on' == strtolower($_SERVER['HTTPS']) )
      return true;
    if ( '1' == $_SERVER['HTTPS'] )
      return true;
  } elseif ( isset($_SERVER['SERVER_PORT']) &amp;&amp; ( '443' == $_SERVER['SERVER_PORT'] ) ) {
    return true;
  }
  return false;
}
----

port443でELBにきてるのがインスタンスに行くときにはport80で行ってしまうため、
$_SERVER[‘HTTPS’]がonにならず、リダイレクトループに突入する感じです。

公式でも触れられているのですが、見つけるのが大変でした。。。 +
https://codex.wordpress.org/Function_Reference/is_ssl

[source, rust]
----
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
    $_SERVER['HTTPS'] = 'on';
----

ふむ、なんか強引な感じがしなくもないですが、
公式ではこんな感じみたいですね。

他にも色々やり方はありますが、これにて作業完了！

## 今回の件で考えたこと感じたこと
作業中お手伝いくださったY氏、N氏ともお話したのですが、強く感じたのはWordPressも当然古くなってくるということです。
今回色々困ったのは以下のような潮流があるからではないでしょうか。

- 多くの検索エンジンがhttpsを推奨しだした
- 安価になったりで証明書を取得しやすくなった
- ロードバランサーなども個人での利用が容易になってきた

ざっくり言ってしまえばセキュア化だとかクラウド化という流れの中で、 +
設計当時の思想ではそのまま適合できない部分が出てきたって感じなのでしょうか。 +
当たり前っちゃ当たり前ですよね、10年以上経っているわけですから。

Matt Mullenweg氏は
https://ja.wordpress.org/2013/06/05/ten-good-years/[「すばらしき10年間」]というポストの中で +

[quote, 'https://ja.wordpress.org/2013/06/05/ten-good-years/[WordPress › Ten Good Years]']
____
WordPressのコードには美しいといえないものもあります。WordPressが始まった頃、僕たちの多くはまだPHPを学んでいる途中だったのです。でも、常にユーザーにとっての体験がなるべくスムーズになるように努めてきました。
____

と環境の変化に対応する中でもあくまでユーザ(非エンジニアであることが多い)の体験が最も重要であるとの姿勢を強く見せています。

変化に適応し続けなければシステムとして死んでしまう、 +
しかし企業がリスクを取りたくないためソフトウェアをクローズに保有してしまう、 +
WordPressはオープンソースだからこそあるべき姿を純粋に追い続けることができたりするのかもしれません。

さらに、同氏はオープンソースについて +
イシン株式会社出版のTECH TSUSHINの4月号において +
「_オープンソースはセキュリティが高く、信用でき、機能的で_」
あると述べています。 +
考え方こそ変えていかなければ、生き残ることは難しいのですね。 +
窓のガラスですら完全に静止することはないのですから。

// ちなみに、東京大学名誉教授である養老孟司氏は +
// 「_自分が変われば世界も変わる_」
// と変化について触れているようです。(※要出典)

日々勉強し、受容し、咀嚼していくことが、人もシステムも必要ですね。

こちらからは以上です。