= 未経験だったけど社会人になってエンジニアになった話
:published_at: 2016-04-21
:hp-alt-title: 
:hp-tags: FirstPost,Oz

こんにちは。  
弊社エンジニアグループでは**まだ**一番若手の3年目エンジニア小笹です。  
今後はともかく現在は主にリストファインダーというサービスの開発を担当してます。

さてさて桜も散り、4月も半ばを過ぎまして、  
日々の生活も少しずつ落ち着いてきているのではないでしょうか。  
特に新入社員となった皆々様におかれまして研修に勤しんでいるケースが多いことと思われます。

そんな中、  
就活関連の話題として  
**「未経験だけどエンジニアになりました。」**  
もしくは  
**「未経験歓迎！エンジニア職募集！！」**、  
**「プログラミングができれば今後食うに困らない」**的な話題を見かけることが増えてきました。

なので今回の投稿では  
**実際に未経験からエンジニアになった**私の視点からエンジニアへの理解のBeforeAfterについてざっくり考えてみることでそんな潮流について思考を広げてみたいと思います。

## 経緯
そもそもなんで私が未経験なのにエンジニアになったかと超速で語ります。  
※詳しい話は直接[コンタクト](https://www.facebook.com/yuki.ozasa "FaceBook")下さい。

まず、イノベーションに総合職として内定をもらってから  
リストファインダーのカスタマーサポートとして学生アルバイトをさせていただきました。

その日々の業務の中で、お客様からのご要望・挙動のおかしい箇所・時間のかかる対応に  
少なからず効率化の余地を感じておりました。  


当時はまだサービスの開発部分を外出しにしている部分もあったのでそういう状況だったのですが、
そういう事情はあまり理解できずフラストレーションが溜まっていました。

なのでものすごくざっくり言えば**自分がエンジニアになれば解決する・改善する**と思い、  
**エンジニアになろうと思い始め、自己学習を始めました。**

その自己学習に対する姿勢やイノベーション社内のエンジニア人材不足などの要因もあり、  
晴れてイノベーション初の新卒エンジニアとして配属されることになりました。

その後、いい意味でまっさらな教育環境で何やらかんやらありつつも、  
会社に家庭教師的な人を呼んでいただいてマンツーマンで教えてもらったり、  
イノベーション以外の会社にお邪魔して開発をしたり、  
などなどして未経験なりに色々吸収してまいりました。

## まとめという名の本筋
そうして周りの人々の多大なるご支援のお陰様をもちまして  
どうにかこうにかエンジニアっぽい仕事ができてきたのですが、  
入社前と今では以下の点について大きく認識が変わりました。

1. プログラミングという言葉
2. エンジニアという職種
3. 近くに聞ける人がいること(コミュニティ)の重要性

### 1. プログラミングという言葉
プログラミング=「プログラムを書くこと」だと思っていましたが、結構違いました。  
今の感覚ですが、**「コンピュータの気持ちになること」**がそうなのかなぁと思います。

論理的に思考ができるのであれば、プログラムを書くこと自体は正直そんなに難しいことではなくて、  
**「よりよく書くこと」**もしくは**「新しいものに追従すること」**の方がよっぽど難しいということもわかってきました。

**「よりよく書く」**には数学やコンピュータサイエンス的な知識が必要ですし、  
**「新しいものに追従すること」**は継続的に学ぶことというよりもなぜその技術が出てきたのか、根本の仕組みや流れを知ることが必要だと思います。

それらは確かに今まで全くの**未経験**でかなりの**ビハインド**だと認識しています。

今、この辺りを本を読んだりしながら勉強してますが、
実は入社1年目の秋頃にも同じように勉強しようとしたことがありました。

でもその時にはまだまだプログラミング=「プログラムを書くこと」だと思っていましたし、
自分自身のスキル不足もあって目の前の仕事とその知識が紐づくイメージはなく、あまり必要性を感じられませんでした。  
なので今の方が学習への意欲は高く、また業務中にも理解する瞬間があるため**身になってる感**があります。

### 2.エンジニアという職種
エンジニアは「プログラムを書く人」だと思っていましたが、Re:結構違いました。

それ以外にもやれる範囲はとてつもなく広く、  
だからこそスペシャリストがいたりジェネラリストがいたり、  
果てにはエンジニアってなんやねん話が出てくるのだと思いました。

勿論定義自体は重要ではありません、エンジニア同士の認識の話です。  
「エンジニアです」と言われて「あ、あなたも！」とはあんまりならないですね。

### 3. 近くに聞ける人がいること(コミュニティ)の重要性
プログラミングは一人でできるから、  
エンジニアは一人でもどうにかなる、  
そう思っていた時期が私にもありました。

今思うと、エンジニアにおける持続的で効率的な成長には**近くに人がいた方がいい**と思います。  
人の仕事を横から見て盗むことや昔の経験を聞くことって、ものすごく大事です。

社外の方ですがお世話になったTさん、Yさん、Tさん、Nさんは勿論、  
社内の**メンバーの技術や知識は本やWebよりも圧倒的に為になります。**

よくググる力とかって言いますが、  
ググること自体を目的にせず、意識し続けられるのなら聞いた方が早いです。当たり前ですが。  
あと、ググるでいうと信頼性の話があるのでそこは気をつけたいところですね。

ちなみに私の場合は入社当初社内にエンジニアのメンバーが少なかったので  
外の人に聞くケースが多かったで**社内にエンジニアがいないとダメってことにはならない**ので注意。

#### 盗みの例

例えば盗んだ技術やなんやらでいうと  
Linuxコマンドとかがあります。

以前打ったコマンドとかを調べたい時に、私のような若輩者ですと  

`history`

などと打って自分がむやみやたらに  

`cd`  

していることに絶望したりして、  
「以前打ったコマンドとかを調べたい」という欲求自体が減退しかねない状況は稀によくあります。


そんなある日、  
先輩のLinux捌き(?)を横で見させていただいたのですが、  
某氏、「なんだっけな」と過去の自分の行動を思い出そうとしながら

`history | grep 'xxxx'`

と打ったではありませんか。

***衝撃を受けました。***  
そんなニッチな(?)技、少なくとも検索してホイホイ出てくるもんじゃない気がします。  
考えてみれば簡単な技なんですけれども、これによってパイプラインの理解が進んだ気がしますね。  
近くにできる人がいてよかった！！ありがとうございます！！

## オチ
はい、色々ごにょごにょ書きましたが、  
プログラミングだとかエンジニアだとか技術だとかって  

**結局その人がそれを好きじゃないと続いていかないんじゃないかと思い始めてます。**

こちらからは以上です。