= 新卒未経験のbigenがプログラムの構造って面白いって思った話
:published_at: 2016-12-16
:hp-alt-title: ProgramingArchitectureAndMath
:hp-tags: MVC,Architecture,Math,Bigen

はじめまして、**bigen**です。

今年の１０月から入社した、**新卒（ほぼ）未経験**のひよこエンジニアです。 +
軽く経歴を紹介しますと、

- 1991年9月  京都に生まれる
- 2010年4月  PCで遊ぶのが好き（コーディングとかはしない）なので、京都大学工学部情報学科へ入学
- 2013年4月  麻雀が好きなので留年
- 2014年7月  麻雀が好きなので最高位戦日本プロ麻雀協会に入会
- 2016年9月  麻雀はいったん休憩にして、真面目に数学を勉強して卒業
- 2016年１０月2.5留年を経て、イノベーションへ入社

という感じです。 +
大学では線形代数とかをやっていたので、 +
研究で使う計算（積分したり行列計算したり）ぐらいのプログラムは書けたんですが、 +
プロダクトやアプリを作るような経験は全くなしでした。 +

そんな僕が、真面目にプログラミングを初めてみて、 +
**「やっぱり計算機とかプログラミングの概念って学者が作ったんだなぁ」と感じて面白かった話**です。 +
 +

#### 「モデル」という言葉

例えばごく基本的な考え方として「*MVCモデル*」というものがあります（最近勉強した）。 +
サービスの構造を +

1. 目に見える部分（*View*)
1. なにか入力を与える部分(*Controler*)
1. なかでごちゃごちゃやる部分（*Model*）

で分離しようという考え方ですが、 +
最後の「なかでごちゃごちゃやる部分」に「Model」なんて名前をつけるのはいかにも学者っぽいですね。 +
 +
 学術領域では「入力と出力にある関係があった時に、決められたある枠組みの中でその入出力関係を記述したもの」をモデルと呼びます（ちょっと語弊があるかも）。 +
 小難しいことはおいといて、普通に生きてたら「モデル」なんて言葉は芸能人とかプラモデルぐらいにしか使わないわけですよ。 +
 そんな言葉が普通に出てきてるのが面白いなぁと思いました。 +
 +
 
#### オブジェクト志向って数学そのもの

あと、「**オブジェクト志向**」という言葉も勉強中で超難しいなーとか思ってるわけですが、 +
「クラス」「サブクラス」といった概念は、よく考えたら線形代数でモロに出てくる概念でした。 +
 +
 このことに気づいた瞬間、 +
 様々な「クラス」が何重にも折り重なった複雑怪奇なフレームワークも、 +
 線形空間に照らし合わせて考えればすごく理解しやすくなりました。 +
 +
 変数が属する構造体の性質 （数学の言葉だと、**どんな演算が使えて、どんな写像が導入できる集合なのか**） +
 きっちり定義してから変数を扱いましょう、という +
 数学では超超基礎の考え方を「プログラミング」の構造に当てはめているだけなんですね。 +
 +
 
#### まとめ

というわけで、数学とアーキテクチャの話はすごい共通点が多くて、 +
あんなに苦痛だった数学の勉強もやはり役に立つもんだなぁと思って面白かったお話でした。 +