= ウィルゲートさんの社内勉強会に参加の巻

:published_at: 2016-12-22
:hp-alt-title: WILL GATE HACKERS GATE
:hp-tags: Yagasaki,Study,LT


そんなこんなで、年末ですね。

みなさま、師走ってますでしょうか？

矢ヶ崎です。

さて、今回は、https://www.willgate.co.jp/[ウィルゲート]さんの社内勉強会に参加させていただきましたので、

その一部始終をブログらせていただきたいと存じます。

== Hacker’s GATE（仮）

ウィルゲートさんでは、Hacker’s GATE（仮）”※仮までが正式名称とのことです”という名前の社内技術勉強会が開催されているようです。

もともとは、新卒１年目の方がこのHacker’s GATE（仮）を初めて、社内に浸透していったそうです。すごい！！！

詳細は、https://www.willgate.co.jp/blog/2327/[新卒1年目の社員が立ち上げたエンジニアのHackerな欲を満たす「Hacker’s GATE（仮）」とは]をご覧いただければと思います。

今回は社内技術勉強会ですが、2周年・そしてクリスマス会ということで、社外の方もまぜまぜして開催してみよう！となったそうで、そこに食いついて参加させていただきました〜。

ちなみにこの日12/14は、弊社も創立記念日！ということで、なんかアニバってカニバってましたが、とってもおめでたくテンションがあがりました！

そんなこんなで、以下、まとめです！

== とっても素敵なオフィス

訪れて早速ウェルカムな雰囲気でお出向いただき、軽くオフィス案内をしていただきつつ、ちょっと雑談し、Hacker’s GATE（仮）開始！

と同時に、ピザ＆ドリンクで乾杯！！！




== LT大会

そんななか、わたくは、

===== 弊社のマーケティングオートメーションツール、List Finderのトラッキング部分のサーバサイドは、AWS API Gateway + Lambda + SQS で非機能要件をあんまり気にしなくて良くしました。（運用チームの枕が高くなりました）

という、大変内容の薄っぺらいお話をさせていただき、すぐにピザとビールをいただきました。

他の方々は、

===== Amazon Dashボタンであれこれしたぜ！
とか

===== Selenium IDEってお手軽ですよ☆
とか

===== Touch Bar に対応した sl コマンド作ったぜ！
とか

===== Composer パッケージを作って登録したぜ！
とか

の内容で、とっても楽しく、勉強になる内容で熱かったです。

ひさびさに技術ネタで涙が出るくらい笑いました！


==== 以上！
