= タイトル考え中
:hp-alt-title: Azure 6
:hp-tags: syoga, log, Azure, Container Instances, container

お久しぶりです、ドラゴンクエスト11でカジノのマジスロにハマり過ぎ、全く冒険が進まない syoga です。

以前の以前の http://tech.innovation.co.jp/2017/04/14/Azure-3.html[記事] 通り、PS4版と3DS版両方購入しましたが、マジスロはPS4版にしか実装されていないため、PS4版を進めざるを得ない状況となっています。

*激アツ*が本当に*アツい*っていいですね！

さて、最近弊社の某プロダクトでは空前の Docker ブーム（？）が到来しております、そんな中 Microsoft Azure で新たなコンテナサービスが発表されましたので、今回はそちらに触れてみようと思います。

## そもそもコンテナって？
皆様ご存知かとは思いますが、自身の復習も兼ねてざっくり記載したいと思います。

### 従来の仮想化について
従来の仮想化というと、物理コンピュータ上にソフトウェアで仮想的なコンピュータを構築したり、ハイパーバイザという専用ソフトウェア上に仮想的なコンピュータを構築するという手段がありました。

#### ホストOS型
物理コンピュータのハードウェア上で実行されているホストOS内で、仮想化ソフトウェアのアプリケーションを立上げ、その中で仮想コンピュータのゲストOSを動作させ、アプリケーションを実行する方法となります。

*ホストOS型の個人的イメージ図* +
図1

ホストOS、ゲストOS両方にリソースを割かれるため、物理コンピュータのスペックによっては動作が重くなるという事がありますが、個人で利用する分にはとても手軽に別環境が作れるのが魅力かと思います。

VirtualBox や VMware Player 等が該当します。

#### ハイパーバイザ型
ホストOSが存在せず物理コンピュータに仮想化用のレイヤーが作成され、その上で仮想コンピュータを動作される仕組みが、ハイパーバイザ型となります。

*ハイパーバイザ型の個人的イメージ図* +
図2

主にサーバで利用される形となり、ハードウェアの BIOS から直接仮想化ソフトウェアを起動する事で、オーバヘッドをより小さくできるという方法です。

ホストOS型の図と比べた通り余白が多くなっていますが、それだけ処理の手続きが少なくて済むという事になっています、図ではゲストOSは1台ですが、通常は複数OSを1台の物理コンピュータ（サーバ）で動作させるケースが多いです。

VMware ESXi や Microsoft Hyper-V 等が該当します。

ホストOS型もハイパーバイザ型も、ホストOSとゲストOSが異なっても大丈夫だけど、仮想コンピュータのハードウェアは物理コンピュータのスペックに依存し、各種リソースの消費量が大きい、自由度が高い仮想化という事が分かりました。

### コンテナについて
上記を踏まえた上でコンテナを利用した仮想化ってなんだろうという事ですが、カーネルが直接物理コンピュータ上に、コンテナという隔離された仮想コンピュータの区画を作成し、その区画を利用するという仕組みになります。

*コンテナ型の個人的イメージ図* +
図3

コンテナを管理するソフトウェアとして、Docker を利用します。

前述した仮想化技術とは異なり、コンテナはホストOS と同一の OS を利用する事で、リソースの消費量が抑えられ、軽量かつ可搬性の高い仮想化という事がわかりました。

カーネルの機能が利用されているため別の OS を利用したいという場合は、コンテナでは実現ができないというデメリットもありますが、今回は特に気にしません。

という訳で…

## それでは Container Instances を利用してみます。
今回は以下のチュートリアルを参考に、Container Instances を利用したいと思います！
https://docs.microsoft.com/ja-jp/azure/container-instances/[Azure Container Instances のドキュメント - チュートリアル]

*■ 必要なもの* +
・Azure アカウント +
・Azure CLI +
・Docker

### コンテナイメージ作成
Microsoft が公開している Node.js のサンプルコードを GitHub からダウンロードします。
```
git clone https://github.com/Azure-Samples/aci-helloworld.git
```

サンプルコードの Dockerfile を確認すると以下の様になっていました。
```
FROM node:8.2.0-alpine
RUN mkdir -p /usr/src/app
COPY ./app/* /usr/src/app/
WORKDIR /usr/src/app
RUN npm install
CMD node /usr/src/app/index.js
```
Alpine Linux という軽量なディストリビューションを利用してベースイメージを作成していますね、後は作業ディレクトリの設定、モジュールのインストールといった具合でした。

さっそくイメージを作成するため、build コマンドを実行します。
```
docker build ./aci-helloworld -t aci-tutorial-app
```
*実行結果*
```
Sending build context to Docker daemon  119.8kB
Step 1/6 : FROM node:8.2.0-alpine
8.2.0-alpine: Pulling from library/node
88286f41530e: Already exists
84f3a4bf8410: Already exists
d0d9b2214720: Already exists
Digest: sha256:c73277ccc763752b42bb2400d1aaecb4e3d32e3a9dbedd0e49885c71bea07354
Status: Downloaded newer image for node:8.2.0-alpine
 ---> 90f5ee24bee2
Step 2/6 : RUN mkdir -p /usr/src/app
 ---> Running in fd2884ac733a
 ---> fa95a2f944df
Removing intermediate container fd2884ac733a
Step 3/6 : COPY ./app/* /usr/src/app/
 ---> ab5086699178
Removing intermediate container 802725fc6fbb
Step 4/6 : WORKDIR /usr/src/app
 ---> 9672fb073fdc
Removing intermediate container 405e6261d157
Step 5/6 : RUN npm install
 ---> Running in 24f54a4b1d92
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.0
npm info lifecycle aci-helloworld@1.0.0~preinstall: aci-helloworld@1.0.0
npm http fetch GET 200 https://registry.npmjs.org/express 604ms
〜 略 〜

added 45 packages in 5.006s
npm info ok
 ---> fc740c1f5333
Removing intermediate container 24f54a4b1d92
Step 6/6 : CMD node /usr/src/app/index.js
 ---> Running in 9ef0205a5e9d
 ---> 5581a6aeecdf
Removing intermediate container 9ef0205a5e9d
Successfully built 5581a6aeecdf
Successfully tagged aci-tutorial-app:latest
```
完了しました。

とりあえずローカルで実行してみます。
```
docker run -d aci-tutorial-app

```
localhost にアクセスすると… +
図4

サンプルページが表示されました。

### Azure Container Registry 
