= 執筆中
:hp-alt-title: Azure 5
:hp-tags: syoga, log, Azure, Computer Vision API, Function App, Node.js, LINE, Repl-AI

お久しぶりです、SREの人 syoga です。今年も後5ヶ月ですが、ログ出して行きましょう。

皆様すでにご存知かもしれませんが「電子レンジで魚が焼ける皿」を買いました。これが凄く便利で、皿に魚（生 or 干物）を載せてレンジでチンするだけで、焼き魚が簡単に作れます！

個人的に感動したので、こちらで共有させていただきました！

まるで魔法のようですね…魔法と言えば我々エンジニアは、魔法のようなクラウドサービスを利用する事が多いかと思います、そう！*AWS*です。

## もしもAWSが使えなかったら…
【ここから超展開】 +
```
『つまり！何が起こるか分からない現在（イマ）だからこそ、
地球外生命体が攻めてきて全世界のAWSデータセンターを、
破壊する可能性だってあるんだ！！』

ΩΩΩ < な、なんだってー!?
```
【ここまで 】
色々なクラウドサービスを利用できた方が良いかなと思い、以前の
http://tech.innovation.co.jp/2017/04/14/Azure-3.html[記事]で、作成した「画像解析Bot」くんを、Azureに移行するための理由を無理矢理作りました。

## AWS < = > Azure
AWS では *Lambda + API GateWay*と*S3*を利用していましたが、Azure では同等の機能として *Function App* と *Storage* があります。

Function App でも Node.js が利用できますので、コードを改良しつつ載せ替えてみます。

■ 改良したい点 +
・お話できるようにする +
・コールバック地獄から脱出 +
・検索ワードを指定しぐるなびの検索ができるようにする +
・Bot の画像と名称を変更する*（緊急）*

それでは早速…

## 準備します
### 1.Function App の作成 
必要な物は Microsoft アカウントとクレジットカードと、後は勇気だけ。 +

詳細な手順については以下の Microsoft Docs を参照下さい。 +
https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-create-serverless-api[Azure Functions を使用したサーバーレス API の作成]

### 2.Strage の作成
必要な物は（略）。 +

詳細な手順については以下の Microsoft Docs を参照下さい。 +
https://docs.microsoft.com/ja-jp/azure/storage/storage-create-storage-account[Azure ストレージ アカウントについて]

プランで変わってきますが、1GB ¥1.53〜¥5.10で利用できます（最初の50TB/月）。

### 3.Redis Cache の作成
ぐるなびでのキーワード指定検索や、下記の Repl-AI で利用するユーザ ID を保存するために、Redis でデータを格納したいと思います。

詳細な手順については以下の Microsoft Docs を参照下さい。 +
https://docs.microsoft.com/ja-jp/azure/redis-cache/cache-dotnet-how-to-use-azure-redis-cache[Azure Redis Cache の使用方法]

れでぃさ〜。

### 4.会話用に利用するRepl-AIのユーザ登録
Repl-AI という

## 会話できるようにする
